# Uncomment the next line to define a global platform for your project
 platform :ios, '10.2'

target 'Flatmates' do
  pod 'RSKImageCropper'
  
  pod 'QBImagePickerController'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Flatmates


  target 'FlatmatesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Flatmates-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Flatmates-tvOS

  target 'Flatmates-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
