
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    increment_build_number(xcodeproj: './ios/Flatmates.xcodeproj') # Increment the build number
    gym(clean: true, scheme: "Flatmates", workspace: "./ios/Flatmates.xcworkspace", export_xcargs: "-allowProvisioningUpdates")
    pilot(username: "joseph@fazzino.net", app_identifier: "com.fazzino.Flatmates", skip_waiting_for_build_processing:true, changelog: changelog) # waiting just takes too long sometimes
  end
end

platform :android do
  lane :beta do
    gradle(task: 'clean', project_dir: "android/") # Clean the Gradle project
    gradle(task: "assemble", build_type: "Release", project_dir: "android/") # Build the Release APK
    supply(track: "beta", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end
end